### ISSUE TITLE
add emails of users to be notified when someone signs up

### ISSUE THREAD

**Issue by cmcnamara87** [uq-eresearch/qldarch-frontend#155] opened 2016-06-19 02:50 UTC
Given that an administrator is logged in
When they go to the admin page
They should be able to see a list of emails to be notified when someone signs up

Given that an administrator is logged in
When they go to the admin page
They should be able to add and remove emails from the list of notification emails

**Comment by agebe** [comment] 2016-07-05 00:25
duplicate of #147

**Closed by agebe** 2016-07-05 00:25 UTC
